<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="task.WithinTest" tests="6" skipped="0" failures="0" errors="0" timestamp="2019-10-03T11:18:49" hostname="Raiyan-PC" time="0.006">
  <properties/>
  <testcase name="testExceptionThrown()" classname="task.WithinTest" time="0.001"/>
  <testcase name="testGetType()" classname="task.WithinTest" time="0.001"/>
  <testcase name="testGetDescription()" classname="task.WithinTest" time="0.001"/>
  <testcase name="testGetWithin()" classname="task.WithinTest" time="0.0"/>
  <testcase name="testToList()" classname="task.WithinTest" time="0.0"/>
  <testcase name="testGetStatusIcon()" classname="task.WithinTest" time="0.0"/>
  <system-out><![CDATA[I threw exception
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
